### ISSUE TITLE
verifiedしよう

### ISSUE THREAD

**Issue by waki285** [SussyRaider/readme#12]
ここをverifiedにしよう
![image](https://user-images.githubusercontent.com/67305123/149318556-70e81989-5218-4f3c-a68b-861da39d00e0.png)

**Comment by AlphaNull16299** [comment]
HOW

**Comment by waki285** [comment]
![image](https://user-images.githubusercontent.com/67305123/149320966-10e9465a-8343-4e76-8903-febda0eb7c91.png)
Teamの設定から行けると思う

**Comment by AlphaNull16299** [comment]
done

**Comment by waki285** [comment]
![image](https://user-images.githubusercontent.com/67305123/149322619-aeda6242-f884-4218-a9d7-9b269ee0778f.png)
good
